# Generated by Django 6.0.7 on 2026-07-21 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
                ('min_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_rating_label', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('INTAKE', 'Intake'), ('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('CHECKED_OUT', 'Checked out'), ('OVERDUE', 'Overdue'), ('BROKEN', 'Broken'), ('UNDER_REPAIR', 'Under repair'), ('RETIRED', 'Retired')], default='INTAKE', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIGHTLY_USED', 'Lightly used'), ('USED', 'Used'), ('DAMAGED', 'Damaged')], default='NEW', max_length=20)),
                ('source', models.CharField(choices=[('PURCHASED', 'Purchased'), ('DONATED', 'Donated')], default='PURCHASED', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='toys/')),
                ('barcode_or_sku', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retired_reason', models.TextField(blank=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toys', to='donations.donation')),
            ],
            options={
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='IntakeRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intake_type', models.CharField(choices=[('DONATION', 'Donation'), ('POST_REPAIR', 'Post-repair'), ('INITIAL_PURCHASE', 'Initial purchase')], max_length=20)),
                ('assessed_condition', models.CharField(choices=[('NEW', 'New'), ('LIGHTLY_USED', 'Lightly used'), ('USED', 'Used'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_records', to='inventory.toy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToyStatusLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='inventory.toy')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='toy',
            index=models.Index(fields=['status'], name='inventory_t_status_1af625_idx'),
        ),
    ]
