# Generated by Django 6.0.7 on 2026-07-24 19:52

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='toy',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, editable=False, null=True),
        ),
    ]
