# Generated by Django 6.0.7 on 2026-07-21 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkouts', '0002_initial'),
        ('inventory', '0001_initial'),
        ('waitlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_by_date', models.DateField()),
                ('pickup_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PICKED_UP', 'Picked up'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('resulting_checkout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='checkouts.checkoutrecord')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.toy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('waitlist_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='waitlist.waitlistentry')),
            ],
            options={
                'ordering': ['-reserved_at'],
                'indexes': [models.Index(fields=['status', 'pickup_deadline'], name='reservation_status_ef44d5_idx')],
            },
        ),
    ]
