# Generated by Django 6.0.7 on 2026-07-21 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('SILVER', 'Silver'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond')], max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('joining_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('renewal_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_concurrent_checkouts', models.PositiveSmallIntegerField()),
                ('loan_period_days', models.PositiveSmallIntegerField()),
                ('complimentary_extension_days', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['joining_fee'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('ACTIVE', 'Active'), ('PENDING_TERMINATION', 'Pending termination'), ('DISCONTINUED', 'Discontinued')], default='PENDING_PAYMENT', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('renewed_through', models.DateField(blank=True, null=True)),
                ('discontinued_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.ledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershiptier')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipSignOff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], default='REQUESTED', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_amount_due', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deposit_amount_returned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deduction_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sign_off', to='memberships.membership')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('refund_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.ledgerentry')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipTierChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deposit_adjustment_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.ledgerentry')),
                ('from_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.membershiptier')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_changes', to='memberships.membership')),
                ('to_tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.membershiptier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user',), name='one_active_membership_per_user'),
        ),
    ]
