# Generated by Django 6.0.7 on 2026-07-21 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_initial'),
        ('checkouts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutrecord',
            name='toy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='inventory.toy'),
        ),
        migrations.AddField(
            model_name='extension',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='checkouts.checkoutrecord'),
        ),
        migrations.AddField(
            model_name='extension',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.ledgerentry'),
        ),
        migrations.AddField(
            model_name='latefeeassessment',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_assessments', to='checkouts.checkoutrecord'),
        ),
        migrations.AddField(
            model_name='latefeeassessment',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.ledgerentry'),
        ),
        migrations.AddIndex(
            model_name='checkoutrecord',
            index=models.Index(fields=['member', 'status'], name='checkouts_c_member__e86daf_idx'),
        ),
        migrations.AddIndex(
            model_name='checkoutrecord',
            index=models.Index(fields=['status', 'current_due_date'], name='checkouts_c_status_2f9a60_idx'),
        ),
    ]
