# Generated by Django 6.0.7 on 2026-07-21 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CONVERTED_TO_RESERVATION', 'Converted to reservation'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=32)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='inventory.toy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'WAITING')), fields=('toy', 'user'), name='unique_active_waitlist_entry')],
            },
        ),
    ]
