# Generated by Django 6.0.7 on 2026-07-21 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('JOINING_FEE', 'Joining fee'), ('DEPOSIT', 'Deposit'), ('RENEWAL_FEE', 'Renewal fee'), ('LATE_FEE', 'Late fee'), ('PAID_EXTENSION_FEE', 'Paid extension fee'), ('DEPOSIT_REFUND', 'Deposit refund'), ('TIER_CHANGE_ADJUSTMENT', 'Tier change adjustment'), ('OTHER', 'Other')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('direction', models.CharField(choices=[('CHARGE', 'Charge (user owes library)'), ('CREDIT', 'Credit (library owes user)')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('marked_paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_marked_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
