# Generated by Django 6.0.7 on 2026-07-21 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('donations', '0001_initial'),
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='related_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='related_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='memberships.membership'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['user', 'status'], name='billing_led_user_id_59567b_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entry_type', 'status'], name='billing_led_entry_t_af393e_idx'),
        ),
    ]
