# Generated by Django 6.0.7 on 2026-07-21 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_INTAKE', 'In intake'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='donation_receipts/')),
                ('summary_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('BOARD_GAME', 'Board game'), ('PUZZLE', 'Puzzle'), ('RIDE_ON', 'Ride-on toy'), ('BUILDING_SET', 'Building set'), ('SOFT_TOY', 'Soft toy'), ('DOLL', 'Doll'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('make', models.CharField(blank=True, max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('age_rating', models.CharField(blank=True, max_length=64)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='donations.donation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
